### ISSUE TITLE
 Implement Feature to List All Job Posts 

### ISSUE THREAD

**Issue by codewithhermes** [codewithhermes/Job-Searching-Web-App#8] opened 2024-10-02 09:47 UTC
Issue: Implement Feature to List All Job Posts in JobService.java
Feature Overview:
The goal of this feature is to allow users to retrieve a list of all job posts in the system. A new method will be implemented in the service layer to return all job posts from the database.

Implementation Details:
Add Get All Jobs Method in JobService:

Implement a method getAllJobs() in JobService.java that retrieves all job posts using the repository.
The method will interact with the JobRepository to fetch all records from the JobPost table.

**Comment by ArshKumar84** [comment] 2024-10-03 15:26
I have made a pull request and solved this issue

**Comment by ashutoshsarap** [comment] 2024-10-11 09:46
Assign this to me

**Comment by ArshKumar84** [comment] 2024-10-11 10:03
The pull request for this issue has been merged but the issue isn't closed yet
Update JobService.java #12

**Closed as completed** 2024-10-12 09:44 UTC
Labels: hacktoberfest, backend, hacktoberfest-accepted
